W4D5/music_app/config/routes.rb
Rails.application.routes.draw do
  resources :users

  resource :session

  resources :bands

  resources :bands do
    resources :albums, only: :new
  end

  resources :albums, only: [:create, :edit, :show, :update, :destroy]
end

W4D5/music_app/app/models/album.rb
class Album < ApplicationRecord
  belongs_to :band,
  foreign_key: :band_id,
  class_name: :Band
end

W4D5/music_app/app/models/band.rb
class Band < ApplicationRecord
  validates :name, presence: true

  has_many :albums,
  foreign_key: :band_id,
  class_name: :Album
end

W4D5/music_app/app/models/user.rb
class User < ApplicationRecord
  validates :email, presence: true, uniqueness: true
  validates :password, length: { minimum: 6, allow_nil: true }
  validates :password_digest, presence: true
  validates :session_token, presence: true, uniqueness: true


  after_initialize :ensure_session_token

  attr_reader :password

  def self.find_by_credentials(email, password)
    user = User.find_by(email: email)
    user && user.is_password?(password) ? user : nil
  end

  def self.generate_session_token
    self.session_token = SecureRandom.urlsafe_base64
  end

  def reset_session_token!
    self.session_token = SecureRandom.urlsafe_base64
    self.save!
    self.session_token
  end

  def ensure_session_token
    self.session_token ||= SecureRandom.urlsafe_base64
  end

  def password=(pw)
    @password = pw
    self.password_digest = BCrypt::Password.create(pw)
  end

  def is_password?(pw)
    BCrypt::Password.new(self.password_digest).is_password?(pw)
  end
end

W4D5/music_app/app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  def show
    @album = Album.find(params[:id])
    render :show
  end

  def new
    @album = Album.new()
    render :new
  end

  def create
    @album = Album.new(album_params)

    if @album.save
      redirect_to band_url(@album.band_id)
    else
      render :new
    end
  end

  def edit
    @album = Album.find(params[:id])
    render :edit
  end

  def update
    @album = Album.find(params[:id])
    if @album.update(album_params)
      redirect_to album_url(@album)
    else
      rendew :new
    end
  end

  def destroy
    @album = Album.find(params[:id])
    @album.destroy
    redirect_to bands_url
  end


  private
  def album_params
    params.require(:album).permit(:title, :year, :band_id, :live)
  end
end

W4D5/music_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :logged_in?, :current_user

  def login!(user)
    @current_user = user
    session[:session_token] = user.reset_session_token!
  end

  def logged_in?
    !!current_user
  end

  def logout!
    current_user.reset_session_token!
    session[:session_token] = nil
    @current_user = nil
  end

  def current_user
    @current_user ||= User.find_by(session_token: session[:session_token])
  end
end

W4D5/music_app/app/controllers/bands_controller.rb
class BandsController < ApplicationController
  def index
    render :index
  end

  def create
    @band = Band.new(band_params)
    if @band.save
      redirect_to band_url(@band)
    else
      render :new
    end
  end

  def new
    render :new
  end

  def show
    @band = Band.find(params[:id])

    render :show
  end

  def edit
    @band = Band.find(params[:id])
    render :edit
  end

  def update
    @band = Band.find(params[:id])
    if @band.update(band_params)
      redirect_to band_url(@band)
    else
      render :index
    end
  end

  def destroy
    @band = Band.find(params[:id])
    @band.destroy
    redirect_to bands_url
  end



  private
    def band_params
      params.require(:band).permit(:name)
    end
end

W4D5/music_app/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    render :login
  end

  def create
    @user = User.find_by_credentials(
      params[:user][:email],
      params[:user][:password]
    )

    if @user
      login!(@user)
      redirect_to bands_url
    else
      render :new
    end
  end

  def destroy
    logout!
    redirect_to new_session_url
  end
end

W4D5/music_app/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    render :index
  end

  def new
    render :new
  end

  def create
    @user = User.new(strong_params)
    if @user.save
      login!(@user)
      redirect_to bands_url
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])

    render :show
  end

private
  def strong_params
    params.require(:user).permit(:email, :password)
  end
end

W4D5/music_app/app/helpers/application_helper.rb
module ApplicationHelper

  def auth_token
    "<input
      type='hidden'
      name='authenticity_token'
      value='#{form_authenticity_token}'
      >".html_safe
    end

end

W4D5/music_app/app/views/albums/_form.html.erb
<% if type == :new %>
  <% action_url = albums_url %>
  <% button_val = "Create New" %>
<% elsif type == :edit %>
  <% action_url = album_url(@album) %>
  <% button_val = "Make Changes" %>
<% end %>


<form action="<%= action_url %>" method="post">
  <% if type == :edit %>
    <input type="hidden" name="_method" value="patch">
  <% end %>

Name <input type="text" name="album[title]" value="<%= album.title %> ">

<br>

Band <select name="album[band_id]">
  <% if album.title.nil? %>
  <option disabled selected> --Please Select-- </option>
  <% end %>
<% Band.all.each do |band| %>
  <% if band.id == album.band_id %>
    <option selected value="<%= band.id %>"> <%= band.name %> </option>
  <% end %>
  <option value="<%= band.id %>"> <%= band.name %> </option>
<% end %>
</select>

<br>

Select one:
 <% if album.live  %>
  <input selected type="radio" name="album[live]" value="true">Live
  <input type="radio" name="album[live]" value="false">Studio
<% elsif album.live == false %>
  <input type="radio" name="album[live]" value="true">Live
  <input selected type="radio" name="album[live]" value="false">Studio
<% else %>
  <input type="radio" name="album[live]" value="true">Live
  <input type="radio" name="album[live]" value="false">Studio
<% end %>

<br>

Year <input type="text" name="album[year]" value= "<%= album.year %>" >

<%= auth_token %>

<input type="submit" value="<%= button_val %>">

</form>

W4D5/music_app/app/views/albums/edit.html.erb
<h1>Edit your album here</h1>

<%= render "form", album: @album, type: :edit %>

W4D5/music_app/app/views/albums/new.html.erb
<h1>Which Album is this?</h1>


<%= render "form", album: @album, type: :new %>

W4D5/music_app/app/views/albums/show.html.erb
<h1 style='text-align: center'>Album Title: <%= @album.title %></h1>
<br>
<h3 style='text-align: center'>By: <%= (Band.find(@album.band_id)).name %></h3>

<form action="<%= edit_album_url(@album) %>" method="get">
  <input type="submit" name="" value="Edit Album">
</form>

<form action= "<%= album_url %>" method="post">
  <input type="hidden" name="_method" value="Delete">
  <%= auth_token %>
  <input type="submit" name="" value="Delete Album">
</form>

<form action="<%= band_url(@album.band_id) %>" method="get">
  <input type="submit" name="" value="Band">
</form>

W4D5/music_app/app/views/bands/edit.html.erb
<h1><%= @band.name %></h1>

<form action="<%= band_url(@band) %> " method="post">
  <input type="hidden" name="_method" value="patch">
  <input type="text" name="band[name]" value=" <%= @band[:name] %>">

  <%= auth_token %>

  <input type="submit" name="" value="Edit This Band">
</form>

W4D5/music_app/app/views/bands/index.html.erb
<ul>
  <% Band.all.each do |band| %>
  <li> <a href= "<%= band_url(band.id) %>" ><%= band.name %> </a></li>
  <br>
  <% end %>
</ul>
<form action="<%= new_band_url %>" method="get">
  <%= auth_token %>
  <input type="submit" name="" value="Add a Band">
</form>

W4D5/music_app/app/views/bands/new.html.erb
<form action="<%= bands_url %> " method="post">
  Band Name: <input type="text" name="band[name]">
  <%= auth_token %>
  <input type="submit" name="" value="Submit">
</form>

W4D5/music_app/app/views/bands/show.html.erb
<h1 style="text-align: center; font-size: 50px;">
  <%= @band.name %>
</h1>
<form class="" action="<%= edit_band_url(@band) %> " method="get">
  <input type="submit" name="" value="Edit This Band">
</form>
<form class="" action="<%= band_url(@band) %> " method="post">
  <input type="hidden" name="_method" value="Delete">
  <%= auth_token %>
  <input type="submit" name="" value="Delete this Band">
</form>
<form class="" action="<%= bands_url %>" method="get">
  <%= auth_token %>
  <input type="submit" name="" value="Home">
</form>

<% albums = Album.where(band_id: @band.id) %>

<% if albums.empty? %>
<% else  %>
ALBUMS
<ul>
<% albums.each do |album| %>
  <li> <a href = "<%= album_url(album) %>"> <%= album.title %></a></li>
<% end %>
</ul>
<% end %>
<a href="<%= new_band_album_url(@band) %> ">ADD AN ALBUM</a>

W4D5/music_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <header style="display: flex; justify-content: flex-end">
    <% if logged_in? %>
      <form style="" action="<%= session_url %>" method="post">
        <input type="hidden" name="_method" value="delete">
        <%= auth_token %>
        <input type="submit" value="LOG OUT!">
      </form>
    <% else %>
      <form style="" action="<%= new_session_url %> " method="get">
        <%= auth_token %>
        <input type="submit" value="LOGIN PAGE">
      </form>
      <form action="<%= new_user_url %> " method="get">
        <%= auth_token %>
        <input type="submit" name="" value="SIGNUP PAGE!">
      </form>
    <% end %>


  </header>
  <h1 style= "color: blue; font-family: courier; text-align: center; font-size: 50px  ">SPINNERS DIGEST</h1>
  <body>
    <%= yield %>
  </body>

  
</html>

W4D5/music_app/app/views/users/index.html.erb
<h1>HOWDY THAR</h1>

W4D5/music_app/app/views/users/new.html.erb
<h1>SIGN UP TODAY OR ELSE</h1>

<form action= "<%= users_url %>" method="post">
  Email: <input type="text" name="user[email]" value="">
  Password: <input type="text" name="user[password]" value="">

  <%= auth_token %>

  <input type="submit" value="Sign Up!">
</form>

W4D5/music_app/app/views/users/show.html.erb
<h1>HELLO USER!</h1>
<p><%= @user.email %></p>

</form>